---
- name: Preparar Servidores com Docker Engine e Docker Compose
  hosts: all
  become: true # Executar comandos como superusuário (sudo)
  tasks:
    - name: Atualizar cache de pacotes (apt)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar pacotes de pré-requisito
      ansible.builtin.apt:
        name: ['ca-certificates', 'curl', 'gnupg']
        state: present

    - name: Adicionar a chave GPG oficial do Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar o repositório do Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Instalar Docker Engine, CLI e containerd
      ansible.builtin.apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        update_cache: yes

    - name: Instalar Docker Compose (v2)
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64" # Verifique a versão mais recente se desejar
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x,o+x'

    - name: Adicionar usuário 'ubuntu' ao grupo 'docker' para executar comandos sem sudo
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes